DROP TABLE "CLIENT";
DROP TABLE "EMPLOYEE";
DROP TABLE "EXPENSE_DETAILS";
DROP TABLE "PROJECT";
DROP TABLE "TEAM";
DROP TABLE "TRAVEL_AGENT";
DROP TABLE "TRAVEL_BUDGET";
DROP TABLE "TRAVEL_DOCUMENT";
DROP TABLE "TRAVEL_REQUEST";
DROP SEQUENCE "CLIENT_SEQ";
DROP SEQUENCE "EMPLOYEE_SEQ";
DROP SEQUENCE "PROJECT_SEQ";
DROP SEQUENCE "TEAM_SEQ";
DROP SEQUENCE "TRAVEL_AGENT_SEQ";
DROP SEQUENCE "TRAVEL_DOCUMENT_SEQ";

