DROP TABLE "CLIENT";
DROP TABLE "EMPLOYEE";
DROP TABLE "EXPENSE_DETAILS";
DROP TABLE "PROJECT";
DROP TABLE "TEAM";
DROP TABLE "TRAVEL_AGENT";
DROP TABLE "TRAVEL_BUDGET";
DROP TABLE "TRAVEL_DOCUMENT";
DROP TABLE "TRAVEL_REQUEST";
DROP SEQUENCE "CLIENT_SEQ";
DROP SEQUENCE "EMPLOYEE_SEQ";
DROP SEQUENCE "PROJECT_SEQ";
DROP SEQUENCE "TEAM_SEQ";
DROP SEQUENCE "TRAVEL_AGENT_SEQ";
DROP SEQUENCE "TRAVEL_DOCUMENT_SEQ";
--------------------------------------------------------
--  DDL for Sequence CLIENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CLIENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPLOYEE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "EMPLOYEE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PROJECT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJECT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TEAM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TEAM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRAVEL_AGENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAVEL_AGENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRAVEL_DOCUMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAVEL_DOCUMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "CLIENT" 
   (	"CLIENT_ID" NUMBER, 
	"CLIENT_NAME" VARCHAR2(80 BYTE), 
	"LOCATION" VARCHAR2(80 BYTE), 
	"CONTACT_NAME" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "EMPLOYEE" 
   (	"EMPLOYEE_ID" NUMBER, 
	"TEAM_ID" NUMBER, 
	"NAME" VARCHAR2(60 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"GENDER" VARCHAR2(1 BYTE), 
	"MANAGER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EXPENSE_DETAILS
--------------------------------------------------------

  CREATE TABLE "EXPENSE_DETAILS" 
   (	"TRAVEL_DOCUMENT_ID" NUMBER, 
	"ACT_TRAVEL_COST" NUMBER(*,0) DEFAULT 0, 
	"ACT_HOTEL_COST" NUMBER(*,0) DEFAULT 0, 
	"ACT_OTHER_COST" NUMBER(*,0) DEFAULT 0, 
	"RECIEPT_FILE_URL" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROJECT
--------------------------------------------------------

  CREATE TABLE "PROJECT" 
   (	"PROJECT_ID" NUMBER, 
	"PROJECT_MANAGER_ID" NUMBER, 
	"PROJECT_NAME" VARCHAR2(80 BYTE), 
	"PROJECT_TYPE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEAM
--------------------------------------------------------

  CREATE TABLE "TEAM" 
   (	"TEAM_ID" NUMBER, 
	"TEAM_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRAVEL_AGENT
--------------------------------------------------------

  CREATE TABLE "TRAVEL_AGENT" 
   (	"AGENT_ID" NUMBER, 
	"ADDRESS" VARCHAR2(80 BYTE), 
	"NAME" VARCHAR2(60 BYTE), 
	"PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"DISCOUNT_DESCRIPTION" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DISCOUNT_DESCRIPTION") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TRAVEL_BUDGET
--------------------------------------------------------

  CREATE TABLE "TRAVEL_BUDGET" 
   (	"TEAMID" NUMBER, 
	"YEAR" VARCHAR2(4 BYTE), 
	"AMOUNT" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRAVEL_DOCUMENT
--------------------------------------------------------

  CREATE TABLE "TRAVEL_DOCUMENT" 
   (	"TRAVEL_DOCUMENT_ID" NUMBER, 
	"CLIENT_ID" NUMBER, 
	"PROJECT_ID" NUMBER, 
	"AGENT_ID" NUMBER, 
	"EMPLOYEE_ID" NUMBER, 
	"CREATED_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	"MGR_STATUS" NUMBER DEFAULT 0, 
	"CFO_STATUS" NUMBER DEFAULT 0, 
	"FIN_STATUS" NUMBER DEFAULT 0, 
	"MGR_LAST_MODIFICATION" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	"CFO_LAST_MODIFICATION" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	"FIN_LAST_MODIFICATION" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRAVEL_REQUEST
--------------------------------------------------------

  CREATE TABLE "TRAVEL_REQUEST" 
   (	"TRAVEL_DOCUMENT_ID" NUMBER, 
	"EST_TRAVEL_COST" NUMBER(*,0) DEFAULT 0, 
	"EST_HOTEL_COST" NUMBER(*,0) DEFAULT 0, 
	"EST_OTHER_COST" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIENT_PK" ON "CLIENT" ("CLIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENT_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIENT_UK1" ON "CLIENT" ("CLIENT_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMPLOYEE_PK" ON "EMPLOYEE" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMPLOYEE_UK1" ON "EMPLOYEE" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EXPENSE_DETAILS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EXPENSE_DETAILS_UK1" ON "EXPENSE_DETAILS" ("TRAVEL_DOCUMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROJECT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT_PK" ON "PROJECT" ("PROJECT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TEAM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAM_PK" ON "TEAM" ("TEAM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TEAM_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAM_UK1" ON "TEAM" ("TEAM_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRAVEL_AGENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAVEL_AGENT_PK" ON "TRAVEL_AGENT" ("AGENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRAVEL_BUDGET_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAVEL_BUDGET_UK1" ON "TRAVEL_BUDGET" ("TEAMID", "YEAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRAVEL_DOCUMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAVEL_DOCUMENT_PK" ON "TRAVEL_DOCUMENT" ("TRAVEL_DOCUMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRAVEL_REQUEST_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAVEL_REQUEST_UK1" ON "TRAVEL_REQUEST" ("TRAVEL_DOCUMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("CLIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CLIENT" ADD CONSTRAINT "CLIENT_UK1" UNIQUE ("CLIENT_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CLIENT" MODIFY ("CLIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIENT" MODIFY ("CLIENT_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "EMPLOYEE" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYEE" MODIFY ("TEAM_ID" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYEE" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EXPENSE_DETAILS
--------------------------------------------------------

  ALTER TABLE "EXPENSE_DETAILS" ADD CONSTRAINT "EXPENSE_DETAILS_UK1" UNIQUE ("TRAVEL_DOCUMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "EXPENSE_DETAILS" MODIFY ("TRAVEL_DOCUMENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJECT
--------------------------------------------------------

  ALTER TABLE "PROJECT" ADD CONSTRAINT "PROJECT_PK" PRIMARY KEY ("PROJECT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PROJECT" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT" MODIFY ("PROJECT_MANAGER_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT" MODIFY ("PROJECT_NAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT" MODIFY ("PROJECT_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEAM
--------------------------------------------------------

  ALTER TABLE "TEAM" MODIFY ("TEAM_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM" MODIFY ("TEAM_NAME" NOT NULL ENABLE);
  ALTER TABLE "TEAM" ADD CONSTRAINT "TEAM_PK" PRIMARY KEY ("TEAM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TEAM" ADD CONSTRAINT "TEAM_UK1" UNIQUE ("TEAM_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRAVEL_AGENT
--------------------------------------------------------

  ALTER TABLE "TRAVEL_AGENT" MODIFY ("AGENT_ID" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL_AGENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL_AGENT" ADD CONSTRAINT "TRAVEL_AGENT_PK" PRIMARY KEY ("AGENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRAVEL_BUDGET
--------------------------------------------------------

  ALTER TABLE "TRAVEL_BUDGET" MODIFY ("TEAMID" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL_BUDGET" MODIFY ("YEAR" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL_BUDGET" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL_BUDGET" ADD CONSTRAINT "TRAVEL_BUDGET_UK1" UNIQUE ("TEAMID", "YEAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRAVEL_DOCUMENT
--------------------------------------------------------

  ALTER TABLE "TRAVEL_DOCUMENT" MODIFY ("TRAVEL_DOCUMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL_DOCUMENT" MODIFY ("MGR_STATUS" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL_DOCUMENT" MODIFY ("CFO_STATUS" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL_DOCUMENT" MODIFY ("FIN_STATUS" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL_DOCUMENT" ADD CONSTRAINT "TRAVEL_DOCUMENT_PK" PRIMARY KEY ("TRAVEL_DOCUMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRAVEL_REQUEST
--------------------------------------------------------

  ALTER TABLE "TRAVEL_REQUEST" MODIFY ("TRAVEL_DOCUMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL_REQUEST" ADD CONSTRAINT "TRAVEL_REQUEST_UK1" UNIQUE ("TRAVEL_DOCUMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_FK1" FOREIGN KEY ("TEAM_ID")
	  REFERENCES "TEAM" ("TEAM_ID") ENABLE;
  ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_FK2" FOREIGN KEY ("MANAGER_ID")
	  REFERENCES "EMPLOYEE" ("EMPLOYEE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXPENSE_DETAILS
--------------------------------------------------------

  ALTER TABLE "EXPENSE_DETAILS" ADD CONSTRAINT "EXPENSE_DETAILS_FK1" FOREIGN KEY ("TRAVEL_DOCUMENT_ID")
	  REFERENCES "TRAVEL_DOCUMENT" ("TRAVEL_DOCUMENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROJECT
--------------------------------------------------------

  ALTER TABLE "PROJECT" ADD CONSTRAINT "PROJECT_FK1" FOREIGN KEY ("PROJECT_MANAGER_ID")
	  REFERENCES "EMPLOYEE" ("EMPLOYEE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRAVEL_BUDGET
--------------------------------------------------------

  ALTER TABLE "TRAVEL_BUDGET" ADD CONSTRAINT "TRAVEL_BUDGET_FK1" FOREIGN KEY ("TEAMID")
	  REFERENCES "TEAM" ("TEAM_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRAVEL_DOCUMENT
--------------------------------------------------------

  ALTER TABLE "TRAVEL_DOCUMENT" ADD CONSTRAINT "TRAVEL_DOCUMENT_FK1" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "EMPLOYEE" ("EMPLOYEE_ID") ENABLE;
  ALTER TABLE "TRAVEL_DOCUMENT" ADD CONSTRAINT "TRAVEL_DOCUMENT_FK2" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "CLIENT" ("CLIENT_ID") ENABLE;
  ALTER TABLE "TRAVEL_DOCUMENT" ADD CONSTRAINT "TRAVEL_DOCUMENT_FK3" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "PROJECT" ("PROJECT_ID") ENABLE;
  ALTER TABLE "TRAVEL_DOCUMENT" ADD CONSTRAINT "TRAVEL_DOCUMENT_FK4" FOREIGN KEY ("AGENT_ID")
	  REFERENCES "TRAVEL_AGENT" ("AGENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRAVEL_REQUEST
--------------------------------------------------------

  ALTER TABLE "TRAVEL_REQUEST" ADD CONSTRAINT "TRAVEL_REQUEST_FK1" FOREIGN KEY ("TRAVEL_DOCUMENT_ID")
	  REFERENCES "TRAVEL_DOCUMENT" ("TRAVEL_DOCUMENT_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger CLIENT_PK_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CLIENT_PK_ID" 
BEFORE INSERT ON CLIENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CLIENT_ID IS NULL THEN
      SELECT CLIENT_SEQ.NEXTVAL INTO :NEW.CLIENT_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CLIENT_PK_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLOYEE_PK_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EMPLOYEE_PK_ID" 
BEFORE INSERT ON EMPLOYEE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.EMPLOYEE_ID IS NULL THEN
      SELECT EMPLOYEE_SEQ.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "EMPLOYEE_PK_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PROJECT_PK_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROJECT_PK_ID" 
BEFORE INSERT ON PROJECT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PROJECT_ID IS NULL THEN
      SELECT PROJECT_SEQ.NEXTVAL INTO :NEW.PROJECT_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PROJECT_PK_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TEAM_PK_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TEAM_PK_ID" 
BEFORE INSERT ON TEAM 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.TEAM_ID IS NULL THEN
      SELECT TEAM_SEQ.NEXTVAL INTO :NEW.TEAM_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TEAM_PK_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRAVEL_AGENT_PK_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRAVEL_AGENT_PK_ID" 
BEFORE INSERT ON TRAVEL_AGENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.AGENT_ID IS NULL THEN
      SELECT TRAVEL_AGENT_SEQ.NEXTVAL INTO :NEW.AGENT_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TRAVEL_AGENT_PK_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRAVEL_DOCUMENT_PK_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRAVEL_DOCUMENT_PK_ID" 
BEFORE INSERT ON TRAVEL_DOCUMENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.TRAVEL_DOCUMENT_ID IS NULL THEN
      SELECT TRAVEL_DOCUMENT_SEQ.NEXTVAL INTO :NEW.TRAVEL_DOCUMENT_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TRAVEL_DOCUMENT_PK_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRAVEL_DOCUMENT_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRAVEL_DOCUMENT_UPDATE" 
BEFORE UPDATE OF FIN_STATUS,CFO_STATUS,MGR_STATUS ON TRAVEL_DOCUMENT 
FOR EACH ROW 
BEGIN
  IF :OLD.FIN_STATUS != :NEW.FIN_STATUS THEN
      :NEW.FIN_LAST_MODIFICATION := CURRENT_TIMESTAMP;
  END IF;
  
  IF :OLD.CFO_STATUS != :NEW.CFO_STATUS THEN
      :NEW.CFO_LAST_MODIFICATION := CURRENT_TIMESTAMP;
  END IF;
  
  IF :OLD.MGR_STATUS != :NEW.MGR_STATUS THEN
      :NEW.MGR_LAST_MODIFICATION := CURRENT_TIMESTAMP;
  END IF;
END;
/
ALTER TRIGGER "TRAVEL_DOCUMENT_UPDATE" ENABLE;
